services:
  - type: web
    name: taskgrid-backend
    env: python
    region: singapore  # closest to India for faster response
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app_mongo.py"
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: taskgrid
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: APP_TIMEZONE
        value: Asia/Kolkata
